import Head from "next/head";

export const Head_C = ({ title }) => {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link
        href="https://fonts.cdnfonts.com/css/clash-display"
        rel="stylesheet"
        
      />
    </Head>
  );
};
